"""Canonical evaluation and source identity; safe mixed-schedule continuation."""

import copy
import json

import pytest

from aopd import __main__ as launcher
from aopd.resume import check_resume, run_identity


@pytest.fixture
def runtime(tmp_path):
    model = tmp_path / "model"
    model.mkdir()
    (model / "model.safetensors").write_bytes(b"weights")
    tau = tmp_path / "tau"
    (tau / "src/tau2").mkdir(parents=True)
    (tau / "src/tau2/__init__.py").write_text("VERSION = 1\n")
    (tau / "data").mkdir()
    (tau / "data/tasks.json").write_text('[{"id": "1", "instruction": "original"}]')
    return {
        "model": str(model),
        "sources": {"tau": str(tau)},
        "student": {"gpus": [0]},
        "services": {"user": {"mode": "api", "base_url": "https://example.invalid/v1", "model": "user"}},
        "roles": {"user": {"service": "user"}},
    }


@pytest.mark.parametrize("relative", ["src/tau2/__init__.py", "data/tasks.json"])
def test_tau_training_resume_binds_source_and_task_contents(runtime, tmp_path, relative):
    run_dir = tmp_path / "train"
    run_dir.mkdir()
    plan = {"recipe": "tau-full", "env": {"TAU2_ROOT": runtime["sources"]["tau"], "TRAIN_STEPS": "100"}}
    identity = check_resume(plan, runtime, run_dir)
    (run_dir / "protocol.json").write_text(json.dumps(identity))
    source = tmp_path / "tau" / relative
    source.write_text(source.read_text() + "\nchanged\n")
    with pytest.raises(ValueError, match="identity|protocol|resume"):
        check_resume(plan, runtime, run_dir)


def test_tau_identity_ignores_generated_bytecode(runtime, tmp_path):
    plan = {"recipe": "tau-full", "env": {"TAU2_ROOT": runtime["sources"]["tau"]}}
    before = run_identity(plan, runtime)
    cache = tmp_path / "tau/src/tau2/__pycache__"
    cache.mkdir()
    (cache / "__init__.cpython-311.pyc").write_bytes(b"generated bytecode")
    assert run_identity(plan, runtime) == before


def test_main_validation_also_binds_tau_source_and_task_data(runtime, tmp_path):
    plan = _main_plan(100)
    plan["env"]["TAU2_ROOT"] = runtime["sources"]["tau"]
    before = run_identity(plan, runtime)
    (tmp_path / "tau/data/tasks.json").write_text('[{"id": "changed"}]')
    assert run_identity(plan, runtime) != before


def _main_plan(steps):
    return {"recipe": "main", "active_roles": [], "env": {"TRAIN_STEPS": str(steps), "N_GPUS": "1"}, "command": ["bash", "train.sh"]}


def test_main_smoke_hydra_overrides_are_resume_critical(runtime):
    formal = _main_plan(1)
    smoke = copy.deepcopy(formal)
    smoke["command"].extend(["env.agentic_mix.bounded_smoke=true", "env.awm.train_max_steps=2", "env.envscaler.train_max_steps=2", "env.max_steps=2"])
    assert run_identity(smoke, runtime) != run_identity(formal, runtime)


@pytest.mark.parametrize("record", ["launch", "schedule"])
@pytest.mark.parametrize("steps", [50, 200])
def test_same_run_main_schedule_change_rejected_before_writes(runtime, tmp_path, monkeypatch, record, steps):
    runtime = {**runtime, "services": {}, "roles": {}}
    run_dir = tmp_path / "main"
    run_dir.mkdir()
    original = _main_plan(100)
    (run_dir / "protocol.json").write_text(json.dumps(run_identity(original, runtime)))
    (run_dir / ".launcher.lock").touch()
    if record == "launch":
        (run_dir / "launch.json").write_text(json.dumps(original))
    else:
        (run_dir / "data").mkdir()
        (run_dir / "data/training_schedule_manifest.json").write_text(json.dumps({"train_steps": 100}))
    before = {p.relative_to(run_dir): p.read_bytes() for p in run_dir.rglob("*") if p.is_file()}

    def must_not_start(*args, **kwargs):
        raise AssertionError("Unsafe schedule resume reached hardware allocation")

    monkeypatch.setattr(launcher, "require_free_gpus", must_not_start)
    with pytest.raises(ValueError, match="schedule|TRAIN_STEPS|new run directory"):
        launcher.run_plan(_main_plan(steps), runtime, run_dir)
    assert {p.relative_to(run_dir): p.read_bytes() for p in run_dir.rglob("*") if p.is_file()} == before


def test_main_checkpoint_extension_into_new_directory_is_allowed(runtime, tmp_path):
    runtime = {**runtime, "services": {}, "roles": {}}
    previous = tmp_path / "previous"
    checkpoint = previous / "checkpoints/global_step_10"
    actor = checkpoint / "actor"
    actor.mkdir(parents=True)
    for kind in ("model", "optim", "extra_state"):
        (actor / f"{kind}_world_size_1_rank_0.pt").write_bytes(b"state")
    (checkpoint / "data.pt").write_bytes(b"dataloader state")
    original = _main_plan(100)
    (previous / "protocol.json").write_text(json.dumps(run_identity(original, runtime)))
    (previous / "launch.json").write_text(json.dumps(original))
    resumed = _main_plan(200)
    resumed["env"]["RESUME_FROM_PATH"] = str(checkpoint)
    target = tmp_path / "new-run"
    assert check_resume(resumed, runtime, target) == run_identity(original, runtime)
    assert not target.exists()
