#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

TRAIN_BATCH="${TRAIN_BATCH:-64}" \
ROLLOUT_N="${ROLLOUT_N:-4}" \
ROLLOUT_MODE="${ROLLOUT_MODE:-state_group}" \
RANDOM_SELECT_PROB="${RANDOM_SELECT_PROB:-0}" \
GPU_MEM_UTIL="${GPU_MEM_UTIL:-0.8}" \
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-65536}" \
STATE_GROUP_ADV_MODE="${STATE_GROUP_ADV_MODE:-mean_then_batch_whiten}" \
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}" \
N_GPUS="${N_GPUS:-8}" \
TP_SIZE="${TP_SIZE:-2}" \
bash "$SCRIPT_DIR/vpr_minesweeper.sh"
